// Augments the Env type generated by `wrangler types` with secrets that live
// in `.dev.vars` and `wrangler secret`. Committed so typecheck doesn't depend
// on a developer running `pnpm cf-typegen` with `.dev.vars` populated first.
declare namespace Cloudflare {
  interface Env {
    TURSO_DATABASE_URL: string;
    TURSO_AUTH_TOKEN: string;
  }
}
