/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PageTwoRouteImport } from './routes/page-two'
import { Route as IndexRouteImport } from './routes/index'

const PageTwoRoute = PageTwoRouteImport.update({
  id: '/page-two',
  path: '/page-two',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/page-two': typeof PageTwoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/page-two': typeof PageTwoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/page-two': typeof PageTwoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/page-two'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/page-two'
  id: '__root__' | '/' | '/page-two'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PageTwoRoute: typeof PageTwoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/page-two': {
      id: '/page-two'
      path: '/page-two'
      fullPath: '/page-two'
      preLoaderRoute: typeof PageTwoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PageTwoRoute: PageTwoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
