/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SlugRouteImport } from './routes/$slug'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LangLangRouteImport } from './routes/lang/$lang'
import { Route as ImagesSplatRouteImport } from './routes/images/$'
import { Route as AdminApiUploadRouteImport } from './routes/admin/api/upload'

const SlugRoute = SlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LangLangRoute = LangLangRouteImport.update({
  id: '/lang/$lang',
  path: '/lang/$lang',
  getParentRoute: () => rootRouteImport,
} as any)
const ImagesSplatRoute = ImagesSplatRouteImport.update({
  id: '/images/$',
  path: '/images/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminApiUploadRoute = AdminApiUploadRouteImport.update({
  id: '/admin/api/upload',
  path: '/admin/api/upload',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$slug': typeof SlugRoute
  '/images/$': typeof ImagesSplatRoute
  '/lang/$lang': typeof LangLangRoute
  '/admin/api/upload': typeof AdminApiUploadRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$slug': typeof SlugRoute
  '/images/$': typeof ImagesSplatRoute
  '/lang/$lang': typeof LangLangRoute
  '/admin/api/upload': typeof AdminApiUploadRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$slug': typeof SlugRoute
  '/images/$': typeof ImagesSplatRoute
  '/lang/$lang': typeof LangLangRoute
  '/admin/api/upload': typeof AdminApiUploadRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/$slug' | '/images/$' | '/lang/$lang' | '/admin/api/upload'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/$slug' | '/images/$' | '/lang/$lang' | '/admin/api/upload'
  id:
    | '__root__'
    | '/'
    | '/$slug'
    | '/images/$'
    | '/lang/$lang'
    | '/admin/api/upload'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SlugRoute: typeof SlugRoute
  ImagesSplatRoute: typeof ImagesSplatRoute
  LangLangRoute: typeof LangLangRoute
  AdminApiUploadRoute: typeof AdminApiUploadRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/$slug': {
      id: '/$slug'
      path: '/$slug'
      fullPath: '/$slug'
      preLoaderRoute: typeof SlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lang/$lang': {
      id: '/lang/$lang'
      path: '/lang/$lang'
      fullPath: '/lang/$lang'
      preLoaderRoute: typeof LangLangRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/images/$': {
      id: '/images/$'
      path: '/images/$'
      fullPath: '/images/$'
      preLoaderRoute: typeof ImagesSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/api/upload': {
      id: '/admin/api/upload'
      path: '/admin/api/upload'
      fullPath: '/admin/api/upload'
      preLoaderRoute: typeof AdminApiUploadRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SlugRoute: SlugRoute,
  ImagesSplatRoute: ImagesSplatRoute,
  LangLangRoute: LangLangRoute,
  AdminApiUploadRoute: AdminApiUploadRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
